name: local
description: Your digital bulletin board
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pocketbase: ^0.14.1
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.2.0
  mocktail: ^1.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - .env
