name: local
description: Go local and get connected to your community.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  heroicons:

  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  tailwind_colors: ^0.3.1
  intl: ^0.18.0
  timeago: ^3.4.0
  platform_maps_flutter: ^1.0.2
  custom_marker: ^1.0.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/pin.svg

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-BoldItalic.ttf
          style: italic
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic


  uses-material-design: true
